name: API Architecture Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Запуск щодня опівночі

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Newman
        run: npm install -g newman
        
      - name: Run API Tests
        run: newman run API_Architecture_Testing.json --reporters cli,junit
        
      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: newman/*.xml
